### ISSUE TITLE
Should be updated

### ISSUE THREAD

**Issue by jbsilva** [snowplow-devops/terraform-google-enrich-pubsub-ce#12]
This module is using `snowplow/snowplow-enrich-pubsub` version `3.0.3`, but version `3.7.0` is already out.

https://github.com/snowplow-devops/terraform-google-enrich-pubsub-ce/blob/91372ebe809dafd8132041a1864753d0084f644d/main.tf#L6

**Comment by jbeemster** [comment]
Hi @jbsilva this project is now up to date again and running v3.8.0
