### ISSUE TITLE
Missing project_id variables.

### ISSUE THREAD

**Issue by EricChea** [snowplow-devops/terraform-google-enrich-pubsub-ce#8]
## Context
Perhaps I'm missing something but when I try to use the `terraform-google-enrich-pubsub-ce` module I run into multiple errors raising an issue with missing `project_id`. It stems from "google_project_iam_member" requiring a `project_id` [line](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam).

**Comment by jbeemster** [comment]
Hi @EricChea we were expecting you to set the project_id directly in your provider block - this then provides this value transiently to all created resources which lets this resource work properly - could you give that a try and see if that unblocks you?

**Comment by EricChea** [comment]
Hi @jbeemster thank you for the response.   Still running into the same issue with missing project errors when creating google_project_iam_member resources.

I tried to be more explicit in two ways.

```
provider "google" {
  project = var.project_id
  region  = var.region
}

...

module "collector_pubsub" {
  source  = "snowplow-devops/collector-pubsub-ce/google"
  version = "0.2.2"
  ...
}

```

Very explicitly.
```
provider "google" {
  project = var.project_id
  region  = var.region
}

...

module "collector_pubsub" {
  source  = "snowplow-devops/collector-pubsub-ce/google"
  version = "0.2.2"
  ...
  providers = {
    google = google
  }
}

```

**Comment by Sebastian2205** [comment]
"[project] - (Required) The project id of the target project. This is not inferred from the provider."
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam

You have to include the variable "Project" in the modules.

**Comment by jbeemster** [comment]
Hi @Sebastian2205 - this did not work in an older provider version which they seem to have changed.

Looking at the CHANGELOG this was introduced in version 4.0.0:

```
resourcemanager: changed the project field to Required in all google_project_iam_* resources (https://github.com/hashicorp/terraform-provider-google/pull/10394)
```

If you drop your provider back to 3.x.x it _should_ work and was what we last tested with.  We will need to go through all of our GCP modules to change this but for the meantime could you give that a go?

**Comment by Sebastian2205** [comment]
@jbeemster 
Thank you for the feedback. 
I will not reset my provider to the 3.xx version. Locally I have adjusted the modules so that I can continue to work without errors. 
I ask you to adjust the modules so that more users do not get problems.

**Comment by jbeemster** [comment]
@Sebastian2205 just updating that we are now fully compatible with v4 of the Google Provider and these updates for project_id have been rolled out!
